import type { Finding } from '@aap-compliance/common';

export const MOCK_FINDINGS: Finding[] = [
  {
    ruleId: 'xccdf_org.ssgproject.content_rule_sshd_set_idle_timeout',
    stigId: 'V-257844',
    title: 'Set SSH Client Alive Interval',
    description:
      'RHEL 9 must be configured so that all network connections associated with SSH traffic are terminated at the end of the session or after 10 minutes of inactivity.',
    fixText: 'Configure the SSH daemon to set the idle timeout interval. Edit /etc/ssh/sshd_config and set ClientAliveInterval to 600.',
    checkText: 'Verify the SSH daemon is configured to terminate idle sessions.',
    severity: 'CAT_I',
    status: 'fail',
    category: 'Access Control',
    disruption: 'low',
    parameters: [
      {
        name: 'var_sshd_set_keepalive',
        label: 'Client Alive Interval (seconds)',
        description: 'SSH client alive interval in seconds',
        type: 'number',
        default: 600,
        value: 600,
      },
    ],
  },
  {
    ruleId: 'xccdf_org.ssgproject.content_rule_sshd_disable_root_login',
    stigId: 'V-257846',
    title: 'Disable SSH Root Login',
    description:
      'RHEL 9 must be configured to prohibit direct login to the root account using remote access via SSH.',
    fixText: 'Edit /etc/ssh/sshd_config and set PermitRootLogin to no.',
    checkText: 'Verify SSH is configured to not allow root login.',
    severity: 'CAT_I',
    status: 'fail',
    category: 'Access Control',
    disruption: 'low',
    parameters: [],
  },
  {
    ruleId: 'xccdf_org.ssgproject.content_rule_enable_fips_mode',
    stigId: 'V-257777',
    title: 'Enable FIPS 140-3 Mode',
    description:
      'RHEL 9 must implement NIST FIPS-validated cryptography for all cryptographic functions.',
    fixText: 'Enable FIPS mode by running: fips-mode-setup --enable',
    checkText: 'Verify the system is in FIPS mode with: fips-mode-setup --check',
    severity: 'CAT_I',
    status: 'fail',
    category: 'System and Communications Protection',
    disruption: 'high',
    parameters: [],
  },
  {
    ruleId: 'xccdf_org.ssgproject.content_rule_accounts_tmout',
    stigId: 'V-257893',
    title: 'Set Account Session Timeout',
    description:
      'RHEL 9 must terminate user sessions after 15 minutes of inactivity.',
    fixText: 'Configure TMOUT in /etc/profile.d/ to 900 seconds.',
    checkText: 'Verify the TMOUT variable is set.',
    severity: 'CAT_II',
    status: 'fail',
    category: 'Access Control',
    disruption: 'low',
    parameters: [
      {
        name: 'var_accounts_tmout',
        label: 'Timeout (seconds)',
        description: 'Session inactivity timeout in seconds',
        type: 'number',
        default: 900,
        value: 900,
      },
    ],
  },
  {
    ruleId: 'xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_chmod',
    stigId: 'V-257910',
    title: 'Audit DAC Permission Changes — chmod',
    description:
      'RHEL 9 must audit all uses of the chmod, fchmod, and fchmodat system calls.',
    fixText: 'Add audit rules for chmod, fchmod, and fchmodat to /etc/audit/rules.d/',
    checkText: 'Verify audit rules for DAC modification.',
    severity: 'CAT_II',
    status: 'fail',
    category: 'Audit and Accountability',
    disruption: 'low',
    parameters: [],
  },
  {
    ruleId: 'xccdf_org.ssgproject.content_rule_configure_crypto_policy',
    stigId: 'V-257778',
    title: 'Configure System Cryptography Policy',
    description:
      'RHEL 9 must configure the system cryptography policy to a level that satisfies security requirements.',
    fixText: 'Update the system cryptography policy: update-crypto-policies --set FIPS',
    checkText: 'Verify the current system-wide crypto policy.',
    severity: 'CAT_II',
    status: 'fail',
    category: 'System and Communications Protection',
    disruption: 'medium',
    parameters: [
      {
        name: 'var_system_crypto_policy',
        label: 'Crypto Policy',
        description: 'System-wide cryptographic policy',
        type: 'select',
        default: 'FIPS',
        value: 'FIPS',
        options: [
          { label: 'DEFAULT', value: 'DEFAULT' },
          { label: 'FIPS', value: 'FIPS' },
          { label: 'FIPS:OSPP', value: 'FIPS:OSPP' },
          { label: 'FUTURE', value: 'FUTURE' },
        ],
      },
    ],
  },
  {
    ruleId: 'xccdf_org.ssgproject.content_rule_package_aide_installed',
    stigId: 'V-257780',
    title: 'Install AIDE',
    description: 'RHEL 9 must install the AIDE package for file integrity monitoring.',
    fixText: 'Install AIDE: dnf install aide',
    checkText: 'Verify AIDE is installed: rpm -q aide',
    severity: 'CAT_II',
    status: 'fail',
    category: 'System and Information Integrity',
    disruption: 'low',
    parameters: [],
  },
  {
    ruleId: 'xccdf_org.ssgproject.content_rule_service_auditd_enabled',
    stigId: 'V-257783',
    title: 'Enable auditd Service',
    description: 'RHEL 9 audit daemon must be enabled and running.',
    fixText: 'Enable auditd: systemctl enable --now auditd',
    checkText: 'Verify auditd is enabled and running.',
    severity: 'CAT_II',
    status: 'pass',
    category: 'Audit and Accountability',
    disruption: 'low',
    parameters: [],
  },
  {
    ruleId: 'xccdf_org.ssgproject.content_rule_grub2_password',
    stigId: 'V-257785',
    title: 'Set GRUB2 Boot Loader Password',
    description:
      'RHEL 9 must require a boot loader password for all boot entries.',
    fixText: 'Set GRUB2 password using grub2-setpassword.',
    checkText: 'Verify GRUB2 is password-protected.',
    severity: 'CAT_I',
    status: 'fail',
    category: 'Configuration Management',
    disruption: 'medium',
    parameters: [],
  },
  {
    ruleId: 'xccdf_org.ssgproject.content_rule_no_empty_passwords',
    stigId: 'V-257832',
    title: 'Prevent Empty Passwords',
    description: 'RHEL 9 must not allow accounts configured with blank or null passwords.',
    fixText: 'Remove nullok from PAM configuration files.',
    checkText: 'Verify no PAM modules allow empty passwords.',
    severity: 'CAT_I',
    status: 'pass',
    category: 'Authentication',
    disruption: 'low',
    parameters: [],
  },
  {
    ruleId: 'xccdf_org.ssgproject.content_rule_disable_ctrlaltdel_reboot',
    stigId: 'V-257790',
    title: 'Disable Ctrl-Alt-Del Reboot',
    description: 'RHEL 9 must disable the Ctrl-Alt-Del key sequence for rebooting.',
    fixText: 'Mask the ctrl-alt-del.target: systemctl mask ctrl-alt-del.target',
    checkText: 'Verify ctrl-alt-del.target is masked.',
    severity: 'CAT_I',
    status: 'fail',
    category: 'Configuration Management',
    disruption: 'low',
    parameters: [],
  },
  {
    ruleId: 'xccdf_org.ssgproject.content_rule_sysctl_net_ipv4_conf_all_accept_redirects',
    stigId: 'V-257800',
    title: 'Disable ICMP Redirect Acceptance',
    description: 'RHEL 9 must not accept ICMP redirect messages.',
    fixText: 'Set sysctl net.ipv4.conf.all.accept_redirects = 0',
    checkText: 'Verify ICMP redirects are disabled.',
    severity: 'CAT_II',
    status: 'pass',
    category: 'Network Configuration',
    disruption: 'low',
    parameters: [],
  },
  {
    ruleId: 'xccdf_org.ssgproject.content_rule_mount_option_tmp_noexec',
    stigId: 'V-257793',
    title: 'Mount /tmp with noexec',
    description: 'RHEL 9 must mount /tmp with the noexec option.',
    fixText: 'Add noexec to /tmp mount options in /etc/fstab.',
    checkText: 'Verify /tmp is mounted with noexec.',
    severity: 'CAT_II',
    status: 'fail',
    category: 'Configuration Management',
    disruption: 'medium',
    parameters: [],
  },
  {
    ruleId: 'xccdf_org.ssgproject.content_rule_banner_etc_issue',
    stigId: 'V-257795',
    title: 'Configure Login Banner',
    description: 'RHEL 9 must display the Standard Mandatory DoD Notice and Consent Banner before login.',
    fixText: 'Configure the DoD consent banner in /etc/issue.',
    checkText: 'Verify the login banner contains the required text.',
    severity: 'CAT_II',
    status: 'fail',
    category: 'Access Control',
    disruption: 'low',
    parameters: [
      {
        name: 'login_banner_text',
        label: 'Banner Text',
        description: 'Text to display as login banner',
        type: 'string',
        default: 'You are accessing a U.S. Government (USG) Information System (IS)...',
        value: 'You are accessing a U.S. Government (USG) Information System (IS)...',
      },
    ],
  },
  {
    ruleId: 'xccdf_org.ssgproject.content_rule_package_rsyslog_installed',
    stigId: 'V-257810',
    title: 'Install rsyslog',
    description: 'RHEL 9 must install the rsyslog package.',
    fixText: 'Install rsyslog: dnf install rsyslog',
    checkText: 'Verify rsyslog is installed.',
    severity: 'CAT_II',
    status: 'pass',
    category: 'Audit and Accountability',
    disruption: 'low',
    parameters: [],
  },
];
